<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Language_switcher
 *
 * Handles the /language_switcher/switchLang/{lang} URLs generated by the
 * language dropdown in the navbar. Sets the session language and redirects
 * back to the referring page (or home if no valid referrer is available).
 *
 * Without this controller, Google crawls the language-switch links produced
 * by lang_dropdown.php and receives a 404, which is reported as a soft 404
 * in Google Search Console.
 */
class Language_switcher extends CI_Controller {

    /** Languages supported by the application. */
    private $allowed_languages = ['english', 'french'];

    public function __construct() {
        parent::__construct();
        $this->load->model('users_model');
    }

    /**
     * switchLang  Sets the site language and redirects the visitor.
     *
     * @param string $lang  Target language (e.g. "english" or "french").
     */
    public function switchLang($lang = 'english') {
        // Only accept known languages; fall back to english for any other value
        // (e.g. the bot-crawled "maintenance.html" variant).
        if (!in_array($lang, $this->allowed_languages, TRUE)) {
            $lang = 'english';
        }

        $this->session->set_userdata('site_lang', $lang);

        // Persist the language preference in a long-lived cookie so it
        // survives session expiry and browser restarts.
        $this->input->set_cookie([
            'name'     => 'site_lang',
            'value'    => $lang,
            'expire'   => 365 * 24 * 3600,
            'httponly' => TRUE,
            'secure'   => (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off'),
        ]);

        // If a player is logged in, persist the choice to the database so
        // the preference is restored on their next login (on any device).
        if ($this->session->userdata('is_logged_in')) {
            // get_user_id() can return FALSE when the session username no longer
            // matches any row (e.g. deleted account), so guard against it.
            $currentUserID = $this->users_model->get_user_id();
            if ($currentUserID) {
                $this->users_model->set_preferred_lang_DB($currentUserID, $lang);
            }
        }

        // Redirect back to the referring page when it is on the same host,
        // otherwise send the visitor to the home page.
        // parse_url() is used for host comparison to prevent open-redirect
        // attacks via crafted Referer headers (e.g. yourdomain.com.evil.com).
        $referrer      = $this->input->server('HTTP_REFERER');
        $base_host     = parse_url(base_url(), PHP_URL_HOST);
        $referrer_host = $referrer ? parse_url($referrer, PHP_URL_HOST) : null;
        if ($referrer && $referrer_host !== null && $referrer_host === $base_host) {
            redirect($referrer);
        } else {
            redirect('home_controller');
        }
    }
}
