<?php
// English language file for Multi-Mountain Ownership (Empire)
defined('BASEPATH') OR exit('No direct script access allowed');

$lang['empire']['title']                    = 'Resort Empire';
$lang['empire']['intro']                    = 'Expand your ski empire by acquiring subsidiary resorts. Each property generates daily passive revenue and boosts your marketing reach across the group.';

// Subsidiary type names
$lang['empire']['nearby_resort_name']       = 'Smaller Nearby Resort';
$lang['empire']['glacier_resort_name']      = 'High-Altitude Glacier Resort';
$lang['empire']['budget_ski_hill_name']     = 'Budget Ski Hill';

// Subsidiary type descriptions
$lang['empire']['nearby_resort_desc']       = 'A smaller ski resort located close to your main property. Shares your marketing campaigns and benefits from proximity to your existing guest base.';
$lang['empire']['glacier_resort_desc']      = 'An exclusive high-altitude glacier resort open year-round. Significantly boosts your brand prestige and marketing reach.';
$lang['empire']['budget_ski_hill_desc']     = 'An affordable ski hill targeting beginners and budget travellers. Low running costs with steady passive revenue.';

// Purchase form
$lang['empire']['purchase_title']           = 'Acquire a New Property';
$lang['empire']['choose_type']              = 'Property type';
$lang['empire']['choose_name']              = 'Name your new property';
$lang['empire']['name_placeholder']         = 'e.g. Alpine Peaks';
$lang['empire']['btn_purchase']             = 'Acquire property';
$lang['empire']['purchase_price']           = 'Acquisition cost';
$lang['empire']['daily_revenue']            = 'Daily revenue';
$lang['empire']['marketing_bonus']          = 'Marketing bonus';

// Owned subsidiaries table
$lang['empire']['owned_title']              = 'Your Properties';
$lang['empire']['col_name']                 = 'Name';
$lang['empire']['col_type']                 = 'Type';
$lang['empire']['col_daily_revenue']        = 'Daily revenue (€)';
$lang['empire']['col_marketing_bonus']      = 'Marketing bonus';
$lang['empire']['col_purchased_at']         = 'Acquired on';
$lang['empire']['no_subsidiaries']          = 'You do not own any subsidiary resorts yet. Acquire your first property below!';

// Empire stats panel
$lang['empire']['stats_title']              = 'Empire Overview';
$lang['empire']['stats_total_properties']   = 'Properties owned';
$lang['empire']['stats_total_daily_rev']    = 'Combined daily revenue';
$lang['empire']['stats_marketing_bonus']    = 'Combined marketing bonus';

// Shared finances panel
$lang['empire']['finances_title']           = 'Shared Finances';
$lang['empire']['finances_intro']           = 'The figures below show the combined passive revenue generated by all your subsidiary properties. This income is added to your main resort\'s treasury each game day.';
$lang['empire']['main_resort']              = 'Main resort';

// Shared marketing panel
$lang['empire']['marketing_title']          = 'Shared Marketing';
$lang['empire']['marketing_intro']          = 'Owning subsidiary resorts increases the effectiveness of your marketing campaigns. The combined bonus below is applied on top of your standard marketing returns.';

// Feedback messages
$lang['empire']['purchase_success']         = '<div class="alert alert-success text-center">Property acquired successfully! It will start generating revenue from tomorrow.</div>';
$lang['empire']['purchase_failed']          = '<div class="alert alert-danger text-center">The acquisition failed. Please try again or contact us at contact@ski-manager.net.</div>';
$lang['empire']['purchase_insufficient_funds'] = '<div class="alert alert-danger text-center">You do not have enough funds to acquire this property.</div>';
$lang['empire']['purchase_invalid_type']    = '<div class="alert alert-danger text-center">Invalid property type selected.</div>';
$lang['empire']['purchase_invalid_name']    = '<div class="alert alert-danger text-center">Please enter a valid name for the property (letters, numbers, spaces and dashes only).</div>';
$lang['empire']['no_resort']               = '<div class="alert alert-warning text-center">You need to create a resort before managing your empire.</div>';

// ── Franchise Mode ──────────────────────────────────────────────────────────

$lang['empire']['franchise_title']              = 'Franchise Mode';
$lang['empire']['franchise_intro']              = 'Take your empire to the next level: unify your brand across all properties, share specialist staff, balance budgets between resorts, and launch cross-promotional campaigns that drive guests to every resort in your portfolio.';

// Shared Branding
$lang['empire']['franchise_branding_title']     = 'Shared Branding';
$lang['empire']['franchise_branding_intro']     = 'Register a franchise brand and choose a tier to apply a branding bonus across all your subsidiary resorts. Upgrading your tier requires a one-off investment.';
$lang['empire']['franchise_brand_name_label']   = 'Franchise brand name';
$lang['empire']['franchise_brand_tier_label']   = 'Brand tier';
$lang['empire']['franchise_upgrade_cost']       = 'Upgrade cost';
$lang['empire']['franchise_branding_bonus']     = 'Branding bonus';
$lang['empire']['franchise_current_brand']      = 'Current brand';
$lang['empire']['franchise_btn_set_branding']   = 'Set brand';
$lang['empire']['franchise_no_brand']           = 'No franchise brand set yet.';

// Shared Staff
$lang['empire']['franchise_staff_title']        = 'Share Staff';
$lang['empire']['franchise_staff_intro']        = 'Assign experienced staff from your main resort to subsidiary properties. Each shared staff member adds +1% to that property\'s service quality bonus (up to +10%).';
$lang['empire']['franchise_staff_col_resort']   = 'Property';
$lang['empire']['franchise_staff_col_count']    = 'Shared staff';
$lang['empire']['franchise_staff_col_bonus']    = 'Service bonus';
$lang['empire']['franchise_btn_update_staff']   = 'Update';
$lang['empire']['franchise_staff_no_subs']      = 'Acquire at least one subsidiary resort to share staff.';

// Budget Balancer
$lang['empire']['franchise_budget_title']       = 'Balance Budgets';
$lang['empire']['franchise_budget_intro']       = 'Transfer funds between your main resort treasury and individual subsidiary resorts to keep every property financially healthy.';
$lang['empire']['franchise_budget_sub_label']   = 'Subsidiary resort';
$lang['empire']['franchise_budget_amount']      = 'Amount (€)';
$lang['empire']['franchise_budget_direction']   = 'Direction';
$lang['empire']['franchise_to_sub']             = '→ Main to subsidiary';
$lang['empire']['franchise_from_sub']           = '← Subsidiary to main';
$lang['empire']['franchise_btn_transfer']       = 'Transfer';
$lang['empire']['franchise_budget_history']     = 'Recent transfers';
$lang['empire']['franchise_col_subsidiary']     = 'Subsidiary';
$lang['empire']['franchise_col_amount']         = 'Amount (€)';
$lang['empire']['franchise_col_direction']      = 'Direction';
$lang['empire']['franchise_col_date']           = 'Date';
$lang['empire']['franchise_no_transfers']       = 'No transfers recorded yet.';

// Cross-Promotions
$lang['empire']['franchise_promo_title']        = 'Cross-Promotions';
$lang['empire']['franchise_promo_intro']        = 'Launch joint promotional campaigns that span all resorts in your portfolio. Active promotions increase the number of guests visiting every property.';
$lang['empire']['franchise_promo_name_label']   = 'Campaign name';
$lang['empire']['franchise_promo_type_label']   = 'Campaign type';
$lang['empire']['franchise_promo_cost']         = 'Cost';
$lang['empire']['franchise_promo_bonus']        = 'Guest bonus';
$lang['empire']['franchise_promo_duration']     = 'Duration';
$lang['empire']['franchise_promo_days']         = 'days';
$lang['empire']['franchise_btn_launch_promo']   = 'Launch campaign';
$lang['empire']['franchise_active_promos']      = 'Active campaigns';
$lang['empire']['franchise_promo_col_name']     = 'Name';
$lang['empire']['franchise_promo_col_type']     = 'Type';
$lang['empire']['franchise_promo_col_bonus']    = 'Guest bonus';
$lang['empire']['franchise_promo_col_expires']  = 'Expires';
$lang['empire']['franchise_no_promos']          = 'No active cross-promotions.';

// Franchise feedback messages
$lang['empire']['franchise_branding_updated']             = '<div class="alert alert-success text-center">Franchise brand updated successfully!</div>';
$lang['empire']['franchise_branding_failed']              = '<div class="alert alert-danger text-center">Failed to update franchise brand. Please try again.</div>';
$lang['empire']['franchise_staff_updated']                = '<div class="alert alert-success text-center">Shared staff allocation updated.</div>';
$lang['empire']['franchise_staff_failed']                 = '<div class="alert alert-danger text-center">Failed to update staff allocation. Please try again.</div>';
$lang['empire']['franchise_transfer_success']             = '<div class="alert alert-success text-center">Budget transfer completed successfully.</div>';
$lang['empire']['franchise_transfer_failed']              = '<div class="alert alert-danger text-center">Budget transfer failed. Please try again.</div>';
$lang['empire']['franchise_promo_launched']               = '<div class="alert alert-success text-center">Cross-promotion campaign launched!</div>';
$lang['empire']['franchise_promo_failed']                 = '<div class="alert alert-danger text-center">Failed to launch promotion. Please try again.</div>';
$lang['empire']['franchise_invalid_brand_name']           = '<div class="alert alert-danger text-center">Please enter a valid brand name (letters, numbers, spaces and dashes only).</div>';
$lang['empire']['franchise_invalid_tier']                 = '<div class="alert alert-danger text-center">Invalid brand tier selected.</div>';
$lang['empire']['franchise_insufficient_funds']           = '<div class="alert alert-danger text-center">Insufficient funds for this action.</div>';
$lang['empire']['franchise_insufficient_subsidiary_funds'] = '<div class="alert alert-danger text-center">The subsidiary does not have enough funds to transfer.</div>';
$lang['empire']['franchise_invalid_subsidiary']           = '<div class="alert alert-danger text-center">Invalid subsidiary selected.</div>';
$lang['empire']['franchise_invalid_amount']               = '<div class="alert alert-danger text-center">Please enter a valid transfer amount greater than zero.</div>';
$lang['empire']['franchise_invalid_direction']            = '<div class="alert alert-danger text-center">Invalid transfer direction.</div>';
$lang['empire']['franchise_invalid_promo_name']           = '<div class="alert alert-danger text-center">Please enter a valid campaign name (letters, numbers, spaces and dashes only).</div>';
$lang['empire']['franchise_invalid_promo_type']           = '<div class="alert alert-danger text-center">Invalid campaign type selected.</div>';
